* Notes 

This is just going to contain notes from chapter 17 onwards

** 17 | Well Ordering  

A partially ordered set is called well ordered (and its ordering calls a well ordering) if every non-empty subset of it has a smallest element. One consequence of this is that every well-ordered set is totally ordered. 

One of the nicest facts about well ordered sets is that we can prove things about their elements by a process similar to induction. 

Suppose that $S$ is a subset of a well ordered set $X$, and suppose that whenever an element $x$ of $X$ is such that the entire initial segment $s(x)$ is included in $S$, then $x$ itself belongs to $S$; the principle of *transfinite induction* asserts that under these circumstances we must have $S = X$. 

Equivalently, if the presence in a set of all the strict predecessors of an element always implies the presence of the element itself, then the set must contain everything. 

The statement of ordinary induction differs from that of transfinite induction by two respects:

- instead of passing each element from its precessor, pass to each element from the set of all its predecessors
- in transfinite induction there is no assumption about a starting element (such as zero)
 
The second point is more linguistic than conceptual. If $x_0$ is the smallest element of $X$, then $s(x_0)$ is empty and consequently $s(x_0) \subset S$; the hypothesis of the principle of transfinite induction requires therefore than $x_0$ belong to $S$. 

Proof of Transfinite Induction: 

Suppose that $S$ is a subset of a well ordered set $X$, and suppose that whenever an element $x$ of $X$ is such that the entire initial segment $s(x)$ is included in $S$, then $x$ itself belongs to $S$. Now consider the set $X - S$. Since X is well ordered, there must be a minimum value in $X - S$, $x$. However, by our assumption $x$ must belong to $S$ since the entire initial segment is included in $S$. This is a contradiction, as $x$ cannot belong to both $S$ and $X - S$. Thus $X - S$ is empty, and $X = S$.

We say that a well ordered set $A$ is a continuation of a well ordered set $B$ if, in the first place, $B$ is a subset of $A$, if, in fact, $B$ is an initial segment of $A$ and if, finally, the ordering of the elements in $B$ is the same as their ordering in $A$. Thus if $X$ is a well ordered set and if $a$ and $b$ are elements of $X$ with $b < a$, then $s(a)$ is a continuation of $s(b)$, and $X$ is a continuation of both $s(a)$ and $s(b)$. 

*** Well Ordering Theorem

Every set can be well ordered.

A better statement is this: For each set $X$, there is a well ordering with domain $X$. 

Proof: 

We apply Zorn's Lemma. Given the set $X$, consider the collection $W$ of all well ordered subsets of $X$.

The collection $W$ is not empty, because $\varnothing \in W$. If $X \neq \varnothing$, less annoying elements of $W$ can be exhibited. If $C$ is a chain in $W$, then the union $U$ of the sets in $C$ has a unique well ordering that makes $U$ larger than (or equal to) each set in $C$. 

This means that the principal hypothesis of Zorn's lemma has been verified; the conclusion is that there exists a maximal well ordered set, say $M$ in $W$. The set $M$ must be equal to the entire set $X$. 

Reason: If $x$ is an element of $X$ not in $M$, then $M$ can be enlarged by putting $x$ after all the elements of $M$. 
** 18 | Transfinite Recursion 

The process of definition by induction has a transfinite analogue. The ordinary recursion theorem constructs a function on $N$; the raw material is a way of getting the value of the function at each non-zero element $n$ of $N$ from its value at the element preceding $n$. The transfinite analogue constructs a function on any well ordered set $W$; the raw material is a way of getting the value of the function at each element $a$ of $W$ from its values at the predecessors of $a$. 

If $a$ is an element of a well ordered set $W$, and if $X$ is an arbitrary set, then by a sequence of type $a$ in $X$ we shall mean a function from the initial segment of $a$ in $W$ into $X$.

If $U$ is a function from $W$ to $X$, then the restriction of $U$ to the initial segment $s(a)$ of $a$ is an example of a sequence of type $a$ for each $a$ in $W$. In what follows, we shall denote that sequence by $U^a$. 

A sequence function of type $W$ in $X$ is a function whose domain consists of all sequences of type $a$ in $X$, for all elements $a$ in $W$, and whose range is included in $X$. Roughly speaking, a sequence function tells us how to lengthen a sequence; given a sequence that stretches up to (but not including) some element of $W$ we can use a sequence function to tack on one more term. 

*** Transfinite Recursion Theorem 

If $W$ is a well ordered set, and if $f$ is a sequence function of type $W$ in a set $X$, then there exists a unique function $U$ from $W$ into $X$ such that $U(a) = f(U^a)$ for each $a$ in $W$. 

# Proof 

# To prove existence, recall that a function from $W$ to $X$ is a certain kind of subset of $W \times X$; we shall construct $U$ explicitly as a set of ordered pairs. 

# Call a subset $A$ of $W \times X$ f-closed if it has the following property: whenever $a \in W$ and $t$ is a sequence of type $a$ included in $A$, that is, $(c, t(c)) \in A)$ for all $c$ in the initial segment $s(a)$, then $(a, f(t)) \in A$. Since $W \times X$ itself is f-closed, such sets do exist; let $U$ be the intersection of them all. Since $U$ itself is f-closed, it remains only to prove that $U$ is a function. 

# The proof is inductive. Let $S$ be the set of all those elements $c$ of $W$ for which it is indeed true that $(c, x) \in U$ for at most one x. We shall prove that is $s(a) \subset S$, then $a \in S$. 

# To say that $s(a) \subset S$ means that if $c < a$ in $W$, then there exists a unique element $x \in X$ such that $(c, x) \in U$. 

An application of the transfinite recursion theorem is called definition by transfinite induction. 

Two posets (which may also be totally ordered or even well ordered) are called *similar* if there exists an order-preserving one-to-one correspondence between them. More explicitly, to say that posets $X$ and $Y$ are similar means that there exists a one-to-one correspondence, say $f$, from $X$ onto $Y$ such that if $a$ and $b$ are in $X$, then a necessary and sufficient condition that $f(a) \leq f(b)$ in $Y$ is that $a \leq b$ in $X$. A correspondence such as $f$ is sometimes called a similarity. 

A similarity of a well ordered set with a part of itself is a very special kind of mapping. If $f$ is a similarity of a well ordered set $X$ into itself, then $a \leq f(a)$ for each $a \in X$. 

Proof: 

Suppose there are elements $b$ such that $f(b) < b$. If $a < b$, where $b$ is at least 1, then $a \leq f(a)$; it follows, in particular, with $a = f(b)$ that $f(b) \leq f(f(b))$. Since $f(b) < b$, the order preserving character of $f$ implies that $f(f(b)) < f(b)$. The only way out of this contradiction is to admit the impossibility of $f(b) < b$. 

The result of the previous paragraph has 3 especially useful consequences: 

1. If two ordered sets, $X$ and $Y$ are similar at all, then there is just one similarity between them. 
2. A well ordered set is never similar to one of its initial segments
3. The comparability theorem for well ordered sets. If $X$ and $Y$ are well ordered sets, then either $X$ and $Y$ are similar, or one of them is similar to an initial segment of the other.

** 19 | Ordinal Numbers  

What happens if we start from $n$, form its successor, $n^+$, and then form the successor of that ad infinitum? Is there something beyond $n, n^+, (n^+)^+$, etc?

The question calls for a set, $T$, containing $n$, such that each element of $T$, other than $n$, can be obtained from $n$ by the repeated formation of successors. Some terminology:

- a function $f$ whose domain is the set of strict predecessors of some natural number $n$ is an $\omega$ successor function if $f(0) = \omega$ (provided that $n \neq 0$ so that $0 < n$), and $f(m^+) = (f(m))^+$ whenever $m^+ < n$. 

Let $S(n, x)$ be the sentence that says "$n$ is a natural number and $x$ belongs to the range of the $\omega$ successor function with domain $n$." A set $T$ s.t. $x \in T$ iff $S(n, x)$ is true for some $n$ is what we are looking for. 

We know that for each natural number $n$ we are permitted to form the set $\{x: S(n, x)\}$. In other words, for each natural number $n$ there exists a set $F(n)$ such that $x \in F(n)$ iff $S(n, x)$ is true. It seems that none of our methods of set construction up to this point is sufficiently strong to prove the existence of a set $F$ of ordered pairs such that $(n, x) \in F$ iff $x \in F(n)$. To achieve this we need a new set-theoretic principle that, roughly speaking, says that anything intelligent that one can do to the elements of a set yields a set. 

*** Axiom of Substitution 

If $S(a, b)$ is a sentence such that for each $a$ in a set $A$ the set $\{b:S(a, b)\}$ can be formed, then there exists a function $F$ with domain $A$ such that $F(a) = \{b:S(a, b)\}$ for each $a \in A$. 

The chief application of the axiom of substitution is in extending the process of counting far beyond the natural numbers. 

An *ordinal number* is defined as a well ordered set $\alpha$ such that $s(\xi) = \xi$ for all $\xi \in \alpha$; here $s(\xi)$ is the initial segment $\{\eta \in \alpha : \eta < \xi \}$. 

An order (partial or total) in a set $X$ is uniquely determined by its initial segments. If, in other words, $R$ and $S$ are orders in $X$, and if, for each $x \in X$, the set of all $R$-predecessors of $s$ is the same of as the set of all $S$-predecessors of $x$, then $R$ and $S$ are the same. 

** 20 | Sets of Ordinal Numbers 

An ordinal number is by definition a special kind of well ordered set. 

The most elementary fast is that each element of an ordinal number $\alpha$ is at the same time a subset of $\alpha$. In other words, every ordinal number is a transitive set. 

If $\xi$ is an element of an ordinal number $\alpha$, then $\xi$ is a subset of $\alpha$ and consequently $\xi$ is a well ordered set. Furthermore, every initial segment of an ordinal number is itself an ordinal number. 

If two ordinal numbers are similar, then they are equal. 

If $\alpha$ and $\beta$ are ordinal numbers, then they are well ordered sets, and consequently, either they are similar or else one of them is similar to an initial segment of the other. 

If $\alpha$ and $\beta$ are distinct ordinal numbers, then $\beta \in \alpha$, $\beta \subset \alpha$, $\alpha$ is a continuation of $\beta$ are all equivalent to one another. If they hold, we may write $\beta < \alpha$. We know that any two ordinal numbers are comparable. 

Every set of ordinal numbers is even more than totally ordered; they are well ordered. 

Some ordinal numbers are finite (these are the natural numbers). The others are called transfinite; the set of all natural numbers $\mathcal{N}$ is the smallest transfinite ordinal number. Each finite ordinal number, other than 0, has an immediate predecessor. If a transfinite ordinal number has an immediate predecessor $\beta$, then $\alpha = \beta^+$. Not every transfinite ordinal number has an immediate predecessor. Those that do not are called limit numbers. 

Next we show that the concept of an ordinal number is not so special, and that each well ordered set resembles some ordinal number in all essential respects. "Resemblence" here is meant in the technical sense of similarity. An informal statement of the result is that each well ordered set can be counted. 

*** Counting Theorem 

Each well ordered set is similar to a unique ordinal number. 

Proof

Since for ordinal numbers, similarity is the same as equality, uniqueness is obvious. Suppose now that X is a well ordered set and suppose that an element $a$ of $X$ is such that the initial segment determined by each predecessor of $a$ is similar to some (necessarily unique) ordinal number. If $S(x, a)$ is the sentence that says "$\alpha$ is an ordinal number and $s(x) \tilde{=} \alpha$" then, for each $x \in s(a)$, the set $\{\alpha : S(x, a)\}$ can be formed. In fact, that set is a singleton. The axiom of substitution implies the existence of a set consisting exactly of the ordinal numbers similar to the initial segments determined by the predecessors of $a$. It follows, whether $a$ is the immediate successor of one of its predecessors or the supremum of them all, that $s(a)$ is similar to an ordinal number. This argument prepares the way for an application of the principle of transfinite induction; the conclusion being that each initial segment in $X$ is similar to some ordinal number. This, in turn, justifies another application of the axiom of substitution; the final conclusion being that $X$ is similar to some ordinal number. 
 
** 21 | Ordinal Arithmetic 

Suppose that $\{E_i\}$ is a disjoint family of well ordered sets indexed by a well ordered set $I$. The ordinal sum of the family is the union $\cup_i E_i$ ordered as follows. If $a$ and $b$ are elements of the union, with $a \in E_i$ and $b \in E_j$, then $a < b$ means that either $i < j$ or else $i = j$ and $a$ precedes $b$ in the given order of $E_i$.

For each well ordered set $X$, let ord $X$ be the uniquie ordinal number similar to $X$ (if $X$ is finite, then ord $X$ is the same as the natural number #$X$). If $\alpha$ and $\beta$ are ordinal numbers, let $A$ and $B$ be disjoint well ordered sets with ord $A = \alpha$ and ord $B = \beta$, and let $C$ be the ordinal sum of $A$ and $B$. The sum $\alpha + \beta$ is the ordinal number $C$ s.t. $\mathrm{ord} A + \mathrm{ord} B = \mathrm{ord} C$. 

Some of the properties of ordinal numbers are good and others are bad. 

Good: 

- $\alpha + 0 = \alpha$
- $0 + \alpha = \alpha$
- $\alpha + 1 = \alpha^+$
- $\alpha + (\beta + \gamma) = (\alpha + \beta) + \gamma$

The commutative law fails: 

- $1 + \gamma = \gamma$, but $\gamma + 1 = \gamma^+$ 

The ordinal product of two well ordered sets $A$ and $B$ is the cartesian product $A \times B$ with the reverse lexicographic order. In other words, if $(a, b)$ and $(c, d)$ are in $A \times B$, then $(a, b) < (c, d)$ means that either $b < d$ or else $b = d$ and $a < c$. 

The product of $\alpha\beta$ is the ordinal number $C$, s.t. $(ordA)(ordB) = ordC$.

For multiplication: 

- $\alpha 0 = 0$
- $0 \alpha = 0$
- $\alpha 1 = \alpha$
- $1 \alpha = \alpha$
- $\alpha(\beta\gamma) = (\alpha\beta)\gamma$ (associative)
- $\alpha(\beta + \gamma) = \alpha\beta + \alpha\gamma$ (left distributive)

The commutative law for multiplication fails. The right distributive law also fails. 
- $2\gamma = \gamma$, but $\gamma 2 \neq \gamma$
- $(\alpha + \beta)\gamma \neq \alpha\gamma + \alpha\beta$

Similarly for exponentiation 

- $0^\alpha = 0 ;(\alpha \geq 1)$
- $1^\gamma = 1$
- $\alpha^{\beta + \gamma} = \alpha^\beta\alpha^\gamma$
- $\alpha^{\beta\gamma} = (\alpha^\beta)^\gamma$

but not all laws hold

- $(\alpha\beta)^\gamma \neq \alpha^\gamma \beta^\gamma$

** 22 | The Schroder-Bernstein Theorem 

We turn to the problem of comparing the sizes of sets. The problem is to compare the sizes of sets when their elements do not appear to have anything to do with each other. 

For well ordered sets, we have what seems to be a reasonable measure of size, namely, their ordinal number. However, we can not just well order each of our sets and compare the ordinal number of each of them. The trouble is that one set can be well ordered in many ways. 

If $X$ and $Y$ are well ordered sets, then a necessary and sufficient condition that ord $X$ < ord $Y$ is that $X$ be similar to an initial segment of $Y$. It follows that we could compare the ordinal sizes of two well ordered sets even without knowing anything about ordinal numbers; all that we need is the concept of similarity. Similarity is defined for ordered sets. For unordered sets, we would use equivalence ($X \sim Y$ iff there exists a 1-to-1 correspondence between them). If we replace similarity by equivalence, then something like the last paragraph becomes usable. 

If $X$ and $Y$ are sets such that $X$ is equivalent to a subset of $Y$, we shall write $X \tilde{\prec} Y$ 

What can we say about two sets if all we know is that each of them is equivalent to a subset of the other? 

*** Schroder Bernstein Theorem  

If $X \tilde{\prec} Y$ and $Y \tilde{\prec} X$, then $X \sim Y$ 

** 23 | Countable Sets 

If $Y$ dominates $X$, but $X$ does not dominate $Y$, so that $X$ is not equivalent to $Y$, we shall write $X \prec Y$ and we shall say that $Y$ strictly dominates $X$. 

Domination and strict domination can be used to express some of the facts about finite and infinite sets in a neat form. 

A set $X$ is called countable (or denumerable) in case $X \prec N$ and countably infinite in case $X \sim N$. Our main purpose in the sequel is to show that many set-theoretic constructions when performed on countable sets lead again to countable sets. 

If $f$ is a function from $N$ onto a set $X$, then $X$ is countable. It follows that a set $X$ is countable iff there exists a function from any countable set onto $X$. Similarly, if $Y$ is any particular countably infinite set, then a necessary and sufficient condition that a non-empty set $X$ be countable is that there exist a function from $Y$ onto $X$. 

The union of a countably infinite family of countable sets is countable. A corollary is that the Cartesian product of two countable sets is also countable. 

*** Cantor's Theorem 

Every set is strictly dominated by its power set, $X \prec \mathcal{P}(X) \forall X$.

This implies that $X \prec 2^X \forall X$. 

** 24 | Cardinal Arithmetic

Our result of our study of the comparative sizes of sets will be to define a new concept, called cardinal number, and to associate with each set $X$ a cardinal number denoted by card $X$. 

Some properties of cardinal arithmetic:
 
- card $X$ = card $Y$ iff $X \sim Y$
- card $X <$ card $Y$ iff $X \prec Y$
- if $a, b$ are cardinal numbers and if $A, B$ are disjoint sets with card $a = A$ and card $b = B$, then $a + b =$ card $(A \cup B)$.
- if $C, D$ are disjoint sets with card $C = a$ and card $D = b$, then $A \sim C$ and $B \sim D$. It follows that $A \cup B \sim C \cup D$.
- commutative $a + b = b + a$
- associative $a + (b + c) = (a + b) + c$ 

Multiplication and Exponentiation are similarly predictable. 

These are not at all surprising on finite sets, and the result is familiar finite arithmetic. Things are different with at least one infinite term.

- If $a, b$ are cardinal numbers s.t. $a$ is finite and $b$ is infinite, then $a + b = b$. 
- If $a$ is an infinite cardinal number, then $a + a = a$ 
- if $a, b$ are cardinal numbers, at least one of which is infinite, and if $c$ is equal to the larger one, then $a + b = c$
- if $a$ is an infinite cardinal number, then $a*a = a$. 

** 25 | Cardinal Numbers 

In order to define a cardinal number here, we will try to define a cardinal number of a set $X$ as some particular carefully selected set equivalent to $X$. 

Our first problem is to narrow the field. Since we know that every set is equivalent to some ordinal number, it is not unnatural to look for the typical sets, the representative sets, among ordinal numbers. A hopeful sign that this is a good approach is that for each set $X$, the ordinal numbers equivalent to $X$ constitute a set. Which set among the ordinal numbers equivalent to $X$ derserves to be singled out and called the cardinal number of $X$? There is only one natural answer. 

Every set of ordinal numbers is well ordered; the least element of a well ordered set is the only one that seems to clamor for special attention. We are now prepared for a definition: 

A *cardinal number* is an ordinal number $\alpha$ such that if $\beta$ if an ordinal number equivalent to $\alpha$, then $\alpha \leq \beta$. The ordinal numbers with this property have also been called initial numbers. If $X$ is a set, then card $X$, the cardinal number of $X$, is the least ordinal number equivalent to $X$. 

It follows that card $X$ = card $Y$ iff $X \sim Y$. Similarly, the facts about the ordering of ordinal numbers are at the same time facts about the ordering of cardinal numbers. 

One of the special symbols for cardinal numbers that is used very frequently is the first letter of the Hebrew alphabet $\aleph$. Thus, in particular, the smallest transfinite ordinal number, i.e. $N$, is a cardinal number, and as such it is always denoted by $\aleph_0$. In many applications of set theory, an important role is played by the smallest uncountable ordinal number, frequently denoted by $\Omega$. The most important property of $N$ is that it is an infinite well ordered set whose initial segments is finite; correspondingly, the most important property of $\Omega$ is that it is an uncountably infinite well ordered set each of whose initial segments is countable. In $\Omega$'s cardinal role it is always denoted by $\aleph_1$.

How do we get from $\aleph_0$ to $\aleph_1$ by arithmetic operations? The simplest thing that we know to do that starts with $\aleph_0$ and ends up with something larger is to form $2^{\aleph_0}$. The continuum hypothesis asserts, as a guess, that $\aleph_1 = 2^{\aleph_0}$. The generalized continuum hypothesis is the conjecture that $\aleph_{\alpha + 1} = 2^{\aleph_\alpha}$ for each ordinal number $\alpha$.
 
